# ------------------------------------------------------------------------------
# This is an example file to get you started with using
# declarative configuration in Kong.
# ------------------------------------------------------------------------------

# Metadata fields start with an underscore (_)
# Fields that do not start with an underscore represent Kong entities and attributes

# _format_version is mandatory,
# it specifies the minimum version of Kong that supports the format

_format_version: "2.1"

# _transform is optional, defaulting to true.
# It specifies whether schema transformations should be applied when importing this file
# as a rule of thumb, leave this setting to true if you are importing credentials
# with plain passwords, which need to be encrypted/hashed before storing on the database.
# On the other hand, if you are reimporting a database with passwords already encrypted/hashed,
# set it to false.

_transform: true

# Each Kong entity (core entity or custom entity introduced by a plugin)
# can be listed in the top-level as an array of objects:

services:
# Service that requires no protection
- name: synchweb-options
  url: https://192.168.33.10/api/options
  routes:
  - name: option-route
    paths:
    - /api/options

- name: synchweb-authenticate
  url: https://192.168.33.10/api/authenticate
  routes:
  - name: authenticate-route
    paths:
    - /api/authenticate

- name: synchweb
  url: https://192.168.33.10/api

- name: py-ispyb
  url: http://192.168.33.40:5000/ispyb/api/v1

- name: synchweb-logistics-api
  url: https://192.168.33.10/api/shipment/dewars/history
  routes:
  - name: add-history
    paths:
    - /api/shipment/dewars/history
    hosts:
    - ispyb-logistics.diamond.ac.uk

# Can also define routes here...
routes:
- name: synchweb
  service: synchweb
  paths:
    - /api

- name: py-ispyb
  service: py-ispyb
  paths:
    - /api/v1

plugins:
- name: ip-restriction
  service: synchweb-logistics-api
  config:
    allow:
    - 192.168.33.1

# Example to test custom auth module
- name: custom-auth
  service: synchweb-restricted
  config:
    introspection_endpoint: https://192.168.33.10/api/authenticate/check
    authorization_endpoint: https://192.168.33.10/api/options
